apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort:: 80
    nodePOrt: 30000
  selector:
    run: php-apache